### ISSUE TITLE
draft-pack-repo doesn't install; bad url

### ISSUE THREAD

**Issue by squillace** [Azure/homebrew-draft#2]
On mac totally updated.

![image](https://user-images.githubusercontent.com/1422718/32021239-a7110a5e-b987-11e7-9bf8-7ce917efdc7d.png)

**Comment by squillace** [comment]
Nice link at the bottom! made this very easy. :-)

**Comment by bacongobbler** [comment]
You can thank homebrew for that. They must've been annoyed for receiving issues on every third party tap repository ;)

huh. So that error is occurring during https://github.com/Azure/draft-pack-repo/blob/master/scripts/get.sh which is called via `draft init` [here](https://github.com/Azure/homebrew-draft/blob/master/Formula/draft.rb#L17).

Can you try the following for me and paste the output in a [gist](https://gist.github.com)?

```
$ cd $(draft home)/plugins/draft-pack-repo
$ set -x
$ ./scripts/get.sh
$ set +x
```

**Comment by bacongobbler** [comment]
BTW, `rm -rf ~/.draft` won't work with draft installations made via homebrew. The best path forward is `rm -rf $(draft home)` because with homebrew, $DRAFT_HOME is set to /usr/local/etc/draft.

**Comment by squillace** [comment]
additional. I'll post the output of what you requested in a moment.

![image](https://user-images.githubusercontent.com/1422718/32027981-f979c8d0-b9a0-11e7-9203-4b75975c6e61.png)

**Comment by squillace** [comment]
even the binary install can't get the default draft pack. 

```
╰─ draft init
Creating /Users/ralphsquillace/.draft
Creating /Users/ralphsquillace/.draft/plugins
Creating /Users/ralphsquillace/.draft/packs
Adding plugin https://github.com/Azure/draft-pack-repo...
Downloading
curl: (3) <url> malformed
Failed to install draft-pack-repo
\tFor support, go to https://github.com/Azure/draft-pack-repo.
Error: plugin install hook for "pack-repo" exited with error
Error: plugin install hook for "pack-repo" exited with error
```

**Comment by squillace** [comment]
https://gist.github.com/squillace/2419b8f599fdba8d8793b39512cdad46.

**Comment by squillace** [comment]
Closing, as it seems something on my machine is NOT RIGHT.
