### ISSUE TITLE
Homebrew wrapper script clobbers DRAFT_HOME

### ISSUE THREAD

**Issue by tvon** [Azure/homebrew-draft#3]
[Including `DRAFT_HOME` in the wrapper script seems problematic](https://github.com/Azure/homebrew-draft/blob/b4a06864ec26751e828039fe6ab1e9d44faf67c3/Formula/draft.rb#L13).

1. [`draft` defaults to using `$HOME/.draft`](https://github.com/Azure/draft/blob/4e1fb4a39854af20f0383b6ab5550434df80ffe8/cmd/draft/draft.go#L140-L151) which seems reasonable.
2. The wrapper script will not pick up `DRAFT_HOME` in the environment, e.g.:

```sh-session
$ export DRAFT_HOME=$PWD/draft-home
$ draft init
...
$DRAFT_HOME has been configured at /opt/homebrew/etc/draft.
...
```

Overriding on the command line does work, however.

**Comment by bacongobbler** [comment]
The reasoning behind this is because homebrew does not allow packages to write configuration into the user's home directory. The common idiom is to write to [whatever homebrew defines](https://github.com/Azure/homebrew-draft/blob/master/Formula/draft.rb#L13) configuration should be stored. I don't know if there's a way around that.

However, that sounds more like an issue for Draft itself, considering Helm [had some recent issues](https://github.com/kubernetes/helm/issues/2630) regarding HELM_HOME.

**Comment by tvon** [comment]
If I understand correctly, `DRAFT_HOME` is set because the `post_install` runs `draft init` which requires that any files written live under `brew --prefix`.

If that is the case, would it be reasonable to leave `draft init` out of the formula?  Do other installation methods run `draft init`?

**Comment by iameli** [comment]
Cross-referencing: https://github.com/Azure/draft/issues/449

**Comment by bacongobbler** [comment]
@tvon the assumption is that any interaction with `draft` requires a call to `draft init`. It looks like [the helm formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-helm.rb) does not make that assumption, so I think removing `draft init` from the install process is fine. That would fix this problem.
