### ISSUE TITLE
[Question] Can this just be folded into homebrew-core?

### ISSUE THREAD

**Issue by jason-riddle** [Azure/homebrew-draft#5]
It would be nice to not have to tap another repo just to get this package. Also, since this formula doesn't appear to do anything crazy, is there another reason why this should not live in https://github.com/Homebrew/homebrew-core?

**Comment by bacongobbler** [comment]
Hey! This sounds good, however this formula won't be accepted into homebrew-core in its current state due to the [Acceptable Formulae doc](https://docs.brew.sh/Acceptable-Formulae), which states:

> ### We don’t like binary formulae

> Our policy is that formulae in the core tap (homebrew/core) must be open-source and either built from source or produce cross-platform binaries (e.g. Java). Binary-only formulae should go to Homebrew Cask.

While our code and CI pipeline is entirely open source, I've been hesitant to move over to homebrew core for a few reasons:

1. We can merge updates to the formula as soon as a release is cut. On homebrew-core, you have to wait for a maintainer to approve.
2. While we can gather metrics for bottle downloads through bintray, by distributing through a single source (the release assets on Azure Blob Storage), we are able to gather those metrics from a single source, making logistics a little simpler on our end
3. Because we won't be able to re-use the packaged release tarballs and provide a fomula that compiles Draft from source, any time the development process changes we must now change it in THREE places: CI, homebrew, and the dev process itself.

If someone else is willing to maintain a formula on homebrew-core I wouldn't mind, but I'd love to hear if there's a way we can work around those 3 issues pointed out and roll this into core. For now, `brew install azure/draft` is easy enough :)

Hope this helps!

**Comment by jason-riddle** [comment]
Yup, this makes sense. Closing.
